language: node_js
os: linux
node_js: lts/*
cache:
  yarn: true
before_script:
- bin/setup
- yarn list
script: bin/buildSite
deploy:
  provider: pages
  local-dir: guide/public
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    repo: cultureamp/cultureamp-style-guide
    branch: master